# mpv-play-bundle-v0.7
# Stable window behavior
auto-window-resize=no
keepaspect-window=no
force-window-position=no

# Image viewer profile adapted from mpv-image-viewer style defaults
[image-viewer]
profile-restore=copy
background=color
background-color=0.2
mute=yes
osc=no
sub-auto=no
audio-file-auto=no
term-status-msg=
image-display-duration=inf
video-aspect-override=no
scale=spline36
cscale=spline36
dscale=mitchell
dither-depth=auto
correct-downscaling
sigmoid-upscaling
